config/routes.rb
Rails.application.routes.draw do
 	
  root to: 'welcome#view'	
  get 'welcome/:name' , to: 'welcome#view', as: 'welcome'
  get 'contact/contactView'
  get 'team/teamView'

  
  resources :gossips ,:authors, :cities ,:comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes , only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips , through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
		belongs_to :user
		belongs_to :gossip

		validates :content ,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :JoinTagGossip
	has_many :tags ,:through => :JoinTagGossip
	has_many :comments
	has_many :likes
	has_many :users,:through => :likes

	validates :title , presence:true ,length:{in: 3..60}
	validates :content , presence:true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip

	#un user ne peut pas aimer plusieures fois un memes gossip
	#l'ID des gossip dans User.likes sont unique
	validates_uniqueness_of :gossip_id, :scope => :user_id
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
	belongs_to :sender , class_name: "User"
	has_many :receiver , class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :JoinTagGossip
	has_many :gossips,:through => :JoinTagGossip
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city ,optional:true
	has_many :gossips
	has_many :sent_messages,foreign_key:'sender_id',class_name: 'PrivateMessage'
	has_many :comments
	has_many :likes

	#Validates
	validates :first_name , presence: true
	validates :email , presence: true , format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true
	validates :password , presence: true , length:{minimum: 5}
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
  	@gossips = @city.gossips
  	puts @city.name.colorize(:green)
  end

end

app/controllers/gossips_controller.rb
	
class GossipsController < ApplicationController
	before_action :authenticate_user, only: [:new , :create]
	before_action :isMyGossip, only: [:edit, :update ,:destroy]

	def authenticate_user
		unless session[:user_id]
			redirect_to new_session_path
		end
	end

	def isMyGossip
		if( !User.find(session[:user_id]).gossips.ids.include?(params[:id].to_i) )
			redirect_to gossip_path
		end
	end
	
  def show
  	@gossip = Gossip.find(params[:id])
  	@user=@gossip.user
  	@comments= @gossip.comments	
  end

  def new
  	puts "controller new Gossip".colorize(:light_green)

  end

  def create
	  	puts "controller create Gossip".colorize(:light_green)
	  	@gossip = Gossip.new(title: params[:title] ,content: params[:content],user_id: session[:user_id])
	  	puts params[:title].colorize(:light_green), params[:content].colorize(:light_green)
	  	@state = @gossip.save
	  	if @state then # essaie de sauvegarder en base @gossip
	  		flash[:success] = "Votre Gossip a été publié !"
	    	redirect_to  root_path
	  	else
	  		#Reaffiche la page 
	  		puts @gossip.errors.full_messages
	  		render new_gossip_path 
	    end
  end

  def index
  	puts "controller index Gossip".colorize(:light_green)	
  end 

  def edit
   	@gossip = Gossip.find(params[:id])
  end 

  def update
	  	puts "controller update Gossip".colorize(:light_green)
	  	gsp = params[:gossip]
	  	puts gsp[:title].colorize(:light_red),gsp[:content].colorize(:light_green)

		  	@gossip = Gossip.find(params[:id])
		if @gossip.update(title:gsp[:title], content:gsp[:content])then
		    redirect_to gossip_path
		else
		  render :edit
		end
  	end

  	def destroy
  		puts "controller delete Gossip".colorize(:light_green)
  		#Detruit les commentaires avant de détruire le gossip
  		gosp = Gossip.all.find(params[:id])
  		gosp.comments.destroy_all
  		gosp.likes.destroy_all
  		gosp.destroy
 	   	redirect_to  root_path
  	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user, only: [:new, :create,:destroy]

	def authenticate_user
		unless session[:user_id]
			redirect_to new_session_path
		end
	end


	def alreadylike

	end

	def new
		puts "Controller new like".colorize(:green)
		@like = Like.new
	end

	def create
		puts "Controller create like".colorize(:green)
		puts params
		@like = Like.new(user_id:params[:user_id], gossip_id: params[:gossip_id] )
		@state= @like.save
			 if(!@state)
			 	puts @like.errors.full_messages
			 else 		
			 	redirect_to root_path
			 end
	end

	def destroy
		puts "Controller destroy like".colorize(:red)
		puts params
		@like=Like.find(params[:id])
		@like.destroy
		redirect_to root_path
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def teamView
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def Current_user
		User.all.find(session[:user_id])
	end

	def log_in(user)
		session[:user_id]=user.id
		session[:user_name]=user.first_name
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/view.html.erb
<%full_name = "#{@user.first_name} #{@user.last_name}"%>

<div class="row justify-content-center " style="padding-top: 1cm;">	
	<div class="card border-info mb-3" style="width: 50rem;">
		  <div class="card-header bg-transparent border-info"><h3><%= @gossip.title%></h3></div>
		  <div class="card-body ">
		    <p class="card-text"><%= @gossip.content%></p>
		  </div>
		  <div class="card-footer bg-transparent border-info">par : <%=link_to full_name, author_path(id: @user.id )%> le <%=@gossip.created_at%>  	
		  </div>
	</div>
</div>

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MModifier gossip </title>
</head>
	<body>
	    <div class="row justify-content-center">
		<%= form_for(@gossip) do |f| %>

		  <div class="field">
		    <%= f.label :title %><br>
		    <%= f.text_field :title %>
		  </div><br><br>


			<div class="form-group" >
				<div class="field" style=>
			    <%= f.label :content %><br>
			    <%= f.text_area :content, :rows=>10, :cols=>60 %>
    			
			 	</div>
		  	</div>

		  <div class="actions">
		    <%= f.submit %>
		  </div>
			<% end %>		
	    </div>

	    <% if @gossip.errors.any? %>
	    <div class="row justify-content-center "style="padding-top: 1cm;">
			<div class="card card text-white bg-danger mb-3" style="width: 30cm;">
			<div class="card-header text-uppercase font-weight-bold">
			Attention erreur de saisis !
			</div>
			<div class="card-body">
			  <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
			  <ul>
			    <% @gossip.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  </ul>
			</div>
			</div>
		</div>
		<% end %>

	</body>
</html>

app/views/gossips/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Creer un nouveau Gossip</title>
</head>
<body>



    <div class="row justify-content-center">
    	<dir>
	    	<%= form_tag gossips_path(action: 'create'), method: "post" do %>

	      <%= label_tag 'Titre' %>
	      <br />
	      <%= text_field_tag 'title', params[:title] %>
	      <br /> <br />

	      <%= label_tag 'Contenu' %>
	      <br />
	      <%= text_area_tag 'content',params[:content] ,:rows=>7, :cols=>60 %>

	      <br /> <br />

	      <%= submit_tag "Creer Gossip" %>

	    	<% end %>
    	</dir>

    </div>

    <% if @state == false  %>
	    <div class="row justify-content-center "style="padding-top: 1cm;">
			<div class="card card text-white bg-danger mb-3" style="width: 30cm;">
			<div class="card-header text-uppercase font-weight-bold">
			Attention erreur de saisis !
			</div>
			<div class="card-body">
			  <p>Nous n'avons pas réussi à creer le potin pour la (ou les) raison(s) suivante(s) :</p>
			  <ul>
			    <% @gossip.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  </ul>
			</div>
			</div>
		</div>
	<% end %>

</body>
</html>

app/views/gossips/show.html.erb
<%full_name = "#{@user.first_name} #{@user.last_name}"%>
<%if( session[:user_id])then%>
<% thisisMyGossip = User.find(session[:user_id]).gossips.ids.include?(@gossip.id)else thisisMyGossip = false end%>

<div class="row justify-content-center " style="padding-top: 1cm;">	
	<div class="card border-info mb-3" style="width: 50rem;">
		<div class="card-header bg-transparent border-info">
			<h3 class="text-info"><%= @gossip.title %> </h3>
		</div>
		<div class="card-body ">
		    <p class="card-text"><%=@gossip.content%></p>
		</div>
		<div class="card-footer bg-transparent border-info">
			<p>par : <%=link_to full_name, author_path(id: @user.id )%> le <%=@gossip.created_at%> à <%=link_to @user.city.name,city_path(id:@user.city.id)%></p>

			<%if(thisisMyGossip)then%>
				<p><%=link_to "Modifier",edit_gossip_path(id:@gossip.id)%></p>	
				<p><%=link_to "Supprimer", gossip_path(id:@gossip.id), method: :delete, data: { confirm: 'Supprimer definitivement ce gossip ?' }%></p>
			<%end%>
		</div>
		<div class="card-footer bg-transparent border-info">
			<button data-toggle="collapse" data-target="#comments" class="btn btn-info">Commentaires (<%=@comments.size%>)</button>
			<div id="comments" class="collapse">
		    	<dir>
			    <%= form_tag comments_path(action: 'create'), method: "post" do %>
			      <br />
			      <%=hidden_field_tag 'id',params[:id]%>
			      <%= text_area_tag 'content',params[:content] ,:rows=>1, :cols=>65 %>
			      <br /> 
			      <%= submit_tag "Commenter" , class:"btn btn-outline-info "%>

			    <% end %>
		    	</dir>
				<% @comments.each{ |index| %>
				<div class="card-footer bg-transparent border-light">
					<p class="text-right text-secondary">
						<%=index.content%>
					</p>					
					<p class="text-right text-secondary">
						par : <span  class="text-warning" > <%=index.user.first_name%> </span> ,
						<%= link_to "Modifier",edit_comment_path(id:index.id)%>
					</p>
				</div>
				<%} %>
			</div>
		</div>
	</div>
</div>