config/routes.rb
Rails.application.routes.draw do
 	
  root to: 'welcome#view'	
  get 'welcome/:name' , to: 'welcome#view', as: 'welcome'
  get 'contact/contactView'
  get 'team/teamView'

  
  resources :gossips ,:authors, :cities ,:comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes , only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips , through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
		belongs_to :user
		belongs_to :gossip

		validates :content ,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :JoinTagGossip
	has_many :tags ,:through => :JoinTagGossip
	has_many :comments
	has_many :likes
	has_many :users,:through => :likes

	validates :title , presence:true ,length:{in: 3..60}
	validates :content , presence:true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip

	#un user ne peut pas aimer plusieures fois un memes gossip
	#l'ID des gossip dans User.likes sont unique
	validates_uniqueness_of :gossip_id, :scope => :user_id
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
	belongs_to :sender , class_name: "User"
	has_many :receiver , class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :JoinTagGossip
	has_many :gossips,:through => :JoinTagGossip
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city ,optional:true
	has_many :gossips
	has_many :sent_messages,foreign_key:'sender_id',class_name: 'PrivateMessage'
	has_many :comments
	has_many :likes

	#Validates
	validates :first_name , presence: true
	validates :email , presence: true , format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true
	validates :password , presence: true , length:{minimum: 5}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	include SessionHelper
  def show
  	@user = User.find(params[:id])
  end

  def new
  	
  end

  def create
  	puts "controller create User".colorize(:light_green)
	  	@user = User.new(first_name: params[:first_name] ,
	  		last_name: params[:last_name],
	  		email: params[:email],
	  		password: params[:password] ,
	  		password_confirmation: params[:conf_password] ,
	  		city_id: City.ids.sample)
	  	puts params
	  	@state = @user.save
	  	if @state then # essaie de sauvegarder en base @gossip
	    	log_in(@user)
	    	redirect_to  root_path
	  	else
	  		#Reaffiche la page 
	  		puts @user.errors.full_messages
	  		render :new 
	    end
  end

  def method_name
  	
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user, only: [:new, :create,:destroy]

	def authenticate_user
		unless session[:user_id]
			redirect_to new_session_path
		end
	end


	def alreadylike

	end

	def new
		puts "Controller new like".colorize(:green)
		@like = Like.new
	end

	def create
		puts "Controller create like".colorize(:green)
		puts params
		@like = Like.new(user_id:params[:user_id], gossip_id: params[:gossip_id] )
		@state= @like.save
			 if(!@state)
			 	puts @like.errors.full_messages
			 else 		
			 	redirect_to root_path
			 end
	end

	def destroy
		puts "Controller destroy like".colorize(:red)
		puts params
		@like=Like.find(params[:id])
		@like.destroy
		redirect_to root_path
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def teamView
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def Current_user
		User.all.find(session[:user_id])
	end

	def log_in(user)
		session[:user_id]=user.id
		session[:user_name]=user.first_name
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author/viewauthor.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="row justify-content-center "style="padding-top: 1cm;">
		<div class="card text-white bg-dark mb-3 d-flex align-content-center flex-wrap" style="width: 30rem;">
			<%full_name = "#{@user.first_name} #{@user.last_name}"%>
		  <div class="card-header"><h3><%=full_name%></h3></div>
		  <div class="card-body">
		    <p>Age : <%=@user.age%> ans</p>
			<p>Ville : <%=@user.city.name%></p>
			<p>E-mail : <a href="#"><%=@user.email%></a>
			</p>
		  </div>
		</div>
	</div>

</body>
</html>

app/views/authors/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Creer un nouveau profil</title>
</head>
<body>
	<div class="row justify-content-center">
    	<dir>
	    <%= form_tag authors_path(action: 'create'), method: "post" do %>
	      <%= label_tag 'Email *' %>
	      <br />
	      <%= text_field_tag 'email', params[:email]%>
	      <br /> <br />

	      <%= label_tag 'Nom' %>
	      <br />
	      <%= text_field_tag 'last_name', params[:last_name]%>
	      <br /> <br />

	      <%= label_tag 'Prenom' %>
	      <br />
	      <%= text_field_tag 'first_name', params[:first_name]%>
	      <br /> <br />

	      <%= label_tag 'Password *' %>
	      <br />
	      <%= text_field_tag 'password',params[:password]%>

	      <br /> <br />

	      <%= label_tag 'Confirmez password *' %>
	      <br />
	      <%= text_field_tag 'conf_password', params[:conf_password]%>
	      <br /> <br />

	      <%= submit_tag "Creer compte" %>

	      <% end %>
    	</dir>

    	<% if @state == false  %>
	    <div class="row justify-content-center "style="padding-top: 1cm;">
			<div class="card card text-white bg-danger mb-3" style="width: 30cm;">
			<div class="card-header text-uppercase font-weight-bold">
			Attention erreur!
			</div>
			<div class="card-body">
			  <p>Nous n'avons pas réussi à creer le profil pour la (ou les) raison(s) suivante(s) :</p>
			  <ul>
			    <% @user.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  </ul>
			</div>
			</div>
		</div>
	<% end %>

    </div>



</body>
</html>

app/views/authors/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="row justify-content-center "style="padding-top: 1cm;">
		<div class="card bg-light mb-3" style="width: 30cm;">
		<div class="card-header text-uppercase font-weight-bold">
		<%=full_name = "#{@user.first_name} #{@user.last_name}"%>
		</div>
		<div class="card-body">
		    <p>Age : <%=@user.age%> ans</p>
		    <p>Ville : <%=link_to @user.city.name,city_path(id:@user.city.id)%>  </p>
			<p>E-mail : <a href="#"><%=@user.email%></a></p>
			<p>Description : </br><%=@user.description%> </p>
		</div>
		</div>
		</div>
	</div>

</body>
</html>