config/routes.rb
Rails.application.routes.draw do
 	
  root to: 'welcome#view'	
  get 'welcome/:name' , to: 'welcome#view', as: 'welcome'
  get 'contact/contactView'
  get 'team/teamView'

  
  resources :gossips ,:authors, :cities ,:comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes , only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips , through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
		belongs_to :user
		belongs_to :gossip

		validates :content ,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :JoinTagGossip
	has_many :tags ,:through => :JoinTagGossip
	has_many :comments
	has_many :likes
	has_many :users,:through => :likes

	validates :title , presence:true ,length:{in: 3..60}
	validates :content , presence:true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip

	#un user ne peut pas aimer plusieures fois un memes gossip
	#l'ID des gossip dans User.likes sont unique
	validates_uniqueness_of :gossip_id, :scope => :user_id
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
	belongs_to :sender , class_name: "User"
	has_many :receiver , class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :JoinTagGossip
	has_many :gossips,:through => :JoinTagGossip
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city ,optional:true
	has_many :gossips
	has_many :sent_messages,foreign_key:'sender_id',class_name: 'PrivateMessage'
	has_many :comments
	has_many :likes

	#Validates
	validates :first_name , presence: true
	validates :email , presence: true , format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true
	validates :password , presence: true , length:{minimum: 5}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user, only: [:new, :create,:destroy]

	def authenticate_user
		unless session[:user_id]
			redirect_to new_session_path
		end
	end


	def alreadylike

	end

	def new
		puts "Controller new like".colorize(:green)
		@like = Like.new
	end

	def create
		puts "Controller create like".colorize(:green)
		puts params
		@like = Like.new(user_id:params[:user_id], gossip_id: params[:gossip_id] )
		@state= @like.save
			 if(!@state)
			 	puts @like.errors.full_messages
			 else 		
			 	redirect_to root_path
			 end
	end

	def destroy
		puts "Controller destroy like".colorize(:red)
		puts params
		@like=Like.find(params[:id])
		@like.destroy
		redirect_to root_path
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def teamView
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def view
  	@name= "Tantely"
  	@gossips= Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def Current_user
		User.all.find(session[:user_id])
	end

	def log_in(user)
		session[:user_id]=user.id
		session[:user_name]=user.first_name
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/view.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>
			Team de The Gossip Project	
		</title>

	</head>

	<body>
		<% name = params[:name]%>

			<div class="jumbotron jumbotron-fluid text-center" id="jumbo">
				<div class="container justify-content-center">
					<h1 class="text-white">Bienvenue <%=name%> !</h1>
				</div>
			</div>

	<div class="">

	</div>

	<div class="container">
	<div class="row justify-content-center">
		<div>
			<div>
			<%if( session[:user_id])then%>
			<div class="card border border-info border-bottom-0">
				<div class="card-header">
				    <h3>
				    	<span class="badge badge-warning"><%=link_to "Creer un nouveau Gossip",new_gossip_path%></span>
				    </h3>
				</div>
			</div>
			<%end%>
			
			</div>
			<% @gossips.each{ |index| %>
	    	<div class="card border border-info border-bottom-0">
				<div class="card-header">
				    Auteur : <%= index.user.first_name%>
				</div>
				<div class="card-body">
					    <h5 class="card-title"><%=link_to index.title, gossip_path(id: index.id )%></h5>
					    <% liked = index.users.ids.include?( session[:user_id] ) %>
					    <%if(liked)then%>
					    <%id_like = index.likes.find_by(user_id: session[:user_id])%>
					    <%id_like.id%>
					    <%=link_to "J'aime",like_path(id:id_like.id), method: :delete,class:"badge badge-pill badge-primary" %>
					    <%else%>
					    <%=link_to "J'aime",likes_path(user_id: session[:user_id],gossip_id: index.id),method: :post,class:"badge badge-pill badge-secondary"%>
					    <%end%>
				</div>	

			</div>
	    	<%} %>
	   	</div>
	</div>
	</div>
</body>
</html>