config/routes.rb
Rails.application.routes.draw do
 	
  root to: 'welcome#view'	
  get 'welcome/:name' , to: 'welcome#view', as: 'welcome'
  get 'contact/contactView'
  get 'team/teamView'

  
  resources :gossips ,:authors, :cities ,:comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes , only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :gossips , through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
		belongs_to :user
		belongs_to :gossip

		validates :content ,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :JoinTagGossip
	has_many :tags ,:through => :JoinTagGossip
	has_many :comments
	has_many :likes
	has_many :users,:through => :likes

	validates :title , presence:true ,length:{in: 3..60}
	validates :content , presence:true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip

	#un user ne peut pas aimer plusieures fois un memes gossip
	#l'ID des gossip dans User.likes sont unique
	validates_uniqueness_of :gossip_id, :scope => :user_id
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
	belongs_to :sender , class_name: "User"
	has_many :receiver , class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :JoinTagGossip
	has_many :gossips,:through => :JoinTagGossip
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city ,optional:true
	has_many :gossips
	has_many :sent_messages,foreign_key:'sender_id',class_name: 'PrivateMessage'
	has_many :comments
	has_many :likes

	#Validates
	validates :first_name , presence: true
	validates :email , presence: true , format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true
	validates :password , presence: true , length:{minimum: 5}
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def teamView
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def Current_user
		User.all.find(session[:user_id])
	end

	def log_in(user)
		session[:user_id]=user.id
		session[:user_name]=user.first_name
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    
    <title>TheGossipProject</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

          <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd">
            <%if( session[:user_name] ) then nm= session[:user_name] else nm=" " end %>
            <%=link_to "The gossip project", welcome_path(name:nm),class:"navbar-brand"%>
        <button class="navbar-toggler" 
        data-toggle="collapse" data-target = "#navbaritem" >
          
          <a class="navbar-toggler-icon"></a>
        </button>

        <div class="collapse navbar-collapse" id="navbaritem">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">

              <%=link_to "Home", welcome_path(name:nm),class:"nav-link"%>
            </li>
              <li class="nav-item">
                <%= link_to "Contact",contact_contactView_path,class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Team",team_teamView_path,class:"nav-link" %>
              </li>              
                  <div class="btn-group">
                    <button type="button" class="btn btn-infos dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%if( session[:user_id] ) then str="Profile" else str="Login/Sign-up"  end %>
                      <%=str%>
                    </button>
                    <div class="dropdown-menu">
                      <%if( session[:user_id] ) then %>
                      <%= link_to "Se deconnecter", session_path(id:session[:user_id]) ,method:"delete",class:"dropdown-item"%>
                      <%= link_to "Voir profil", author_path(id:session[:user_id]),class:"dropdown-item"%>
                      <%else%>
                      <%= link_to "Se connecter", new_session_path ,class:"dropdown-item"%>
                      <%= link_to "S'inscrire", new_author_path ,class:"dropdown-item"%>
                      <%end%>                      
                    </div>
                  </div>
              </li>
          </ul>

        </div>

      </nav>

  </head>

  <body>
    <%= yield %>
  </body>
</html>